name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Copy files in repos
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./Dockerfile --tag my-cicd-docker-core
