name: Docker Image CI

env:
  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
  HEROKU_EMAIL: ${{secrets.HEROKU_EMAIL}}
  APP_NAME: ${{'dotnet-docker-heroku-api'}}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Copy files in repos
      uses: actions/checkout@v3
    - name: Build the Docker image
      #run: docker build . --file Dockerfile --tag my-cicd-docker-core

      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

# Push the Docker image to Heroku Container Registry
    - name: Publish
      run: |
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
    - name: Heroku logs
        heroku logs --tail --app dotnet-docker-heroku-api

 
