name: .NET

on:
  push:
    branches:
    - master
    #- release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Copy files in repos
      uses: actions/checkout@v3
    - name: Build and deploy the docker image
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        HEROKU_EMAIL: ${{secrets.HEROKU_EMAIL}}
        APP_NAME: ${{'cicd-docker-web-api'}}
      run:
        cd ./WebAppCICD/WebAppCICD.Api
        docker login --username=$HEROKU_EMAIL --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_Name
        
